version: '3.3'

volumes:
  postgres_data: {}

services:
  backend:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: /gunicorn.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env.production
    ports:
      - "8000:8000"

  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env.production
