# Generated by Django 2.1.4 on 2018-12-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181229_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=models.CharField(default='', max_length=100, verbose_name='краткое описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=50, verbose_name='заголовок'),
        ),
    ]
