# Generated by Django 2.1.4 on 2018-12-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181229_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='title',
        ),
    ]
